[package]
name = "taskui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
colored = "2.1.0"
crossterm = "0.27.0"
ratatui = "0.25.0"
serde = "1.0.195"
serde_yaml = "0.9.30"
