name: build-test-lint

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - name: Build
      run: |
        nix build
    - name: Test
      run: |
        nix develop --ignore-environment --command "cargo" "test"
    - name: Lint
      run: |
        nix develop --ignore-environment --command "cargo" "clippy"
